import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script
          id="set-theme"
          dangerouslySetInnerHTML={{
            __html: `
            const params = new URL(document.location).searchParams;
            console.log('✅ head script is running', params);
            const theme = params.get("theme") ?? "light"
            document.documentElement.classList.add(theme)
            `
          }}
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
